In [15]:
import pandas as pd
import numpy as np

# Import Data

In [16]:
general_df = pd.read_csv('data/general.csv')

df = general_df

# Initial Exploration

In [17]:
print (df.head())
print (df.columns)
print (df.shape)
print (df.info())
print (df.describe())
print (df.isnull().sum())

  Facility ID                    Facility Name                     Address  \
0       10001  SOUTHEAST HEALTH MEDICAL CENTER      1108 ROSS CLARK CIRCLE
1       10005         MARSHALL MEDICAL CENTERS  2505 U S HIGHWAY 431 NORTH
2       10006     NORTH ALABAMA MEDICAL CENTER         1701 VETERANS DRIVE
3       10007         MIZELL MEMORIAL HOSPITAL               702 N MAIN ST
4       10008      CRENSHAW COMMUNITY HOSPITAL         101 HOSPITAL CIRCLE

  City/Town State  ZIP Code County/Parish Telephone Number  \
0    DOTHAN    AL     36301       HOUSTON   (334) 793-8701
1      BOAZ    AL     35957      MARSHALL   (256) 593-8310
2  FLORENCE    AL     35630    LAUDERDALE   (256) 768-8400
3       OPP    AL     36467     COVINGTON   (334) 493-3541
4   LUVERNE    AL     36049      CRENSHAW   (334) 335-3374

          Hospital Type                           Hospital Ownership  ...  \
0  Acute Care Hospitals  Government - Hospital District or Authority  ...
1  Acute Care Hospitals  Government - Hospital District or Authority  ...
2  Acute Care Hospitals                                  Proprietary  ...
3  Acute Care Hospitals               Voluntary non-profit - Private  ...
4  Acute Care Hospitals                                  Proprietary  ...

  Count of READM Measures Better Count of READM Measures No Different  \
0                              1                                    8
1                              0                                    8
2                              0                                    7
3                              0                                    7
4                              0                                    2

  Count of READM Measures Worse READM Group Footnote  \
0                             2                  NaN
1                             1                  NaN
2                             2                  NaN
3                             0                  NaN
4                             0                  NaN

  Pt Exp Group Measure Count Count of Facility Pt Exp Measures  \
0                          8                                 8
1                          8                                 8
2                          8                                 8
3                          8                                 8
4                          8                     Not Available

  Pt Exp Group Footnote TE Group Measure Count Count of Facility TE Measures  \
0                   NaN                     12                            10
1                   NaN                     12                            12
2                   NaN                     12                            11
3                   NaN                     12                             7
4                   5.0                     12                             6

   TE Group Footnote
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN

[5 rows x 38 columns]
Index(['Facility ID', 'Facility Name', 'Address', 'City/Town', 'State',
       'ZIP Code', 'County/Parish', 'Telephone Number', 'Hospital Type',
       'Hospital Ownership', 'Emergency Services',
       'Meets criteria for birthing friendly designation',
       'Hospital overall rating', 'Hospital overall rating footnote',
       'MORT Group Measure Count', 'Count of Facility MORT Measures',
       'Count of MORT Measures Better', 'Count of MORT Measures No Different',
       'Count of MORT Measures Worse', 'MORT Group Footnote',
       'Safety Group Measure Count', 'Count of Facility Safety Measures',
       'Count of Safety Measures Better',
       'Count of Safety Measures No Different',
       'Count of Safety Measures Worse', 'Safety Group Footnote',
       'READM Group Measure Count', 'Count of Facility READM Measures',
       'Count of READM Measures Better',
       'Count of READM Measures No Different', 'Count of READM Measures Worse',
       'READM Group Footnote', 'Pt Exp Group Measure Count',
       'Count of Facility Pt Exp Measures', 'Pt Exp Group Footnote',
       'TE Group Measure Count', 'Count of Facility TE Measures',
       'TE Group Footnote'],
      dtype='object')
(5384, 38)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5384 entries, 0 to 5383
Data columns (total 38 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Facility ID                                       5384 non-null   object
 1   Facility Name                                     5384 non-null   object
 2   Address                                           5384 non-null   object
 3   City/Town                                         5384 non-null   object
 4   State                                             5384 non-null   object
 5   ZIP Code                                          5384 non-null   int64
 6   County/Parish                                     5384 non-null   object
 7   Telephone Number                                  5384 non-null   object
 8   Hospital Type                                     5384 non-null   object
 9   Hospital Ownership                                5384 non-null   object
 10  Emergency Services                                5384 non-null   object
 11  Meets criteria for birthing friendly designation  2230 non-null   object
 12  Hospital overall rating                           5384 non-null   object
 13  Hospital overall rating footnote                  2618 non-null   object
 14  MORT Group Measure Count                          5384 non-null   object
 15  Count of Facility MORT Measures                   5384 non-null   object
 16  Count of MORT Measures Better                     5384 non-null   object
 17  Count of MORT Measures No Different               5384 non-null   object
 18  Count of MORT Measures Worse                      5384 non-null   object
 19  MORT Group Footnote                               1875 non-null   float64
 20  Safety Group Measure Count                        5384 non-null   object
 21  Count of Facility Safety Measures                 5384 non-null   object
 22  Count of Safety Measures Better                   5384 non-null   object
 23  Count of Safety Measures No Different             5384 non-null   object
 24  Count of Safety Measures Worse                    5384 non-null   object
 25  Safety Group Footnote                             1994 non-null   float64
 26  READM Group Measure Count                         5384 non-null   object
 27  Count of Facility READM Measures                  5384 non-null   object
 28  Count of READM Measures Better                    5384 non-null   object
 29  Count of READM Measures No Different              5384 non-null   object
 30  Count of READM Measures Worse                     5384 non-null   object
 31  READM Group Footnote                              1088 non-null   float64
 32  Pt Exp Group Measure Count                        5384 non-null   object
 33  Count of Facility Pt Exp Measures                 5384 non-null   object
 34  Pt Exp Group Footnote                             2190 non-null   float64
 35  TE Group Measure Count                            5384 non-null   object
 36  Count of Facility TE Measures                     5384 non-null   object
 37  TE Group Footnote                                 894 non-null    float64
dtypes: float64(5), int64(1), object(32)
memory usage: 1.6+ MB
None
           ZIP Code  MORT Group Footnote  Safety Group Footnote  \
count   5384.000000          1875.000000            1994.000000
mean   53762.267831            11.016000              10.675025
std    27103.733755             7.003106               6.947492
min      603.000000             5.000000               5.000000
25%    32607.250000             5.000000               5.000000
50%    55046.000000             5.000000               5.000000
75%    76125.250000            19.000000              19.000000
max    99929.000000            23.000000              23.000000

       READM Group Footnote  Pt Exp Group Footnote  TE Group Footnote
count           1088.000000            2190.000000         894.000000
mean              15.318015              10.126027          17.557047
std                6.287059               6.801070           4.468452
min                5.000000               5.000000           5.000000
25%                5.000000               5.000000          19.000000
50%               19.000000               5.000000          19.000000
75%               19.000000              19.000000          19.000000
max               22.000000              22.000000          22.000000
Facility ID                                            0
Facility Name                                          0
Address                                                0
City/Town                                              0
State                                                  0
ZIP Code                                               0
County/Parish                                          0
Telephone Number                                       0
Hospital Type                                          0
Hospital Ownership                                     0
Emergency Services                                     0
Meets criteria for birthing friendly designation    3154
Hospital overall rating                                0
Hospital overall rating footnote                    2766
MORT Group Measure Count                               0
Count of Facility MORT Measures                        0
Count of MORT Measures Better                          0
Count of MORT Measures No Different                    0
Count of MORT Measures Worse                           0
MORT Group Footnote                                 3509
Safety Group Measure Count                             0
Count of Facility Safety Measures                      0
Count of Safety Measures Better                        0
Count of Safety Measures No Different                  0
Count of Safety Measures Worse                         0
Safety Group Footnote                               3390
READM Group Measure Count                              0
Count of Facility READM Measures                       0
Count of READM Measures Better                         0
Count of READM Measures No Different                   0
Count of READM Measures Worse                          0
READM Group Footnote                                4296
Pt Exp Group Measure Count                             0
Count of Facility Pt Exp Measures                      0
Pt Exp Group Footnote                               3194
TE Group Measure Count                                 0
Count of Facility TE Measures                          0
TE Group Footnote                                   4490
dtype: int64

# Cleaning the data

In [18]:
def clean_general(df):
    """
    Cleans the hospital general info data by standardizing column names,
    dropping unnecessary columns, converting data types, and handling missing values.
    Args:
        df (pd.DataFrame): The hospital general info data.
    Returns:
        pd.DataFrame: Cleaned hospital_general_info data.
    """
    #standardize the column names
    df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')

    #drop columns that are not needed
    columns_to_drop = [
        'telephone_number', 
        'meets_criteria_for_birthing_friendly_designation',
        'hospital_overall_rating_footnote',
        'mort_group_measure_count',
        'count_of_facility_mort_measures',
        'count_of_mort_measures_no_different',
        'count_of_mort_measures_worse',
        'mort_group_footnote',
        'safety_group_measure_count',
        'count_of_facility_safety_measures',
        'count_of_safety_measures_no_different',
        'count_of_safety_measures_worse',
        'safety_group_footnote',
        'readm_group_measure_count',
        'count_of_facility_readm_measures',
        'count_of_readm_measures_no_different',
        'count_of_readm_measures_worse',
        'readm_group_footnote',
        'pt_exp_group_measure_count',
        'count_of_facility_pt_exp_measures',
        'pt_exp_group_footnote',
        'te_group_measure_count',
        'count_of_facility_te_measures',
        'te_group_footnote', 
         'city/town', 
         'county/parish',
         'hospital_type',
         'emergency_services',
         
    ]
    df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

    #convert zip_code to string (object) to preserve formatting like leading zeros
    if 'zip_code' in df.columns:
        df['zip_code'] = df['zip_code'].astype(str).str.zfill(5)

    #use the correct column names as they appear in the DataFrame (standardized)
    cols_to_convert = [
        'hospital_overall_rating',
        'count_of_mort_measures_better',
        'count_of_safety_measures_better',
        'count_of_readm_measures_better'
    ]
    
    for col in cols_to_convert:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    #replace NaN values with 0 for hospital_overall_rating, 'count_of_mort_measures_better',
    # 'count_of_safety_measures_better', and 'count_of_readm_measures_better'
    df['hospital_overall_rating'].fillna(0, inplace=True)
    df['count_of_mort_measures_better'].fillna(0, inplace=True)
    df['count_of_safety_measures_better'].fillna(0, inplace=True)
    df['count_of_readm_measures_better'].fillna(0, inplace=True)
    return df

In [19]:
#print clean_general(df).head()
cleaned_df = clean_general(df)
print(cleaned_df.head())

  facility_id                    facility_name                     address  \
0       10001  SOUTHEAST HEALTH MEDICAL CENTER      1108 ROSS CLARK CIRCLE
1       10005         MARSHALL MEDICAL CENTERS  2505 U S HIGHWAY 431 NORTH
2       10006     NORTH ALABAMA MEDICAL CENTER         1701 VETERANS DRIVE
3       10007         MIZELL MEMORIAL HOSPITAL               702 N MAIN ST
4       10008      CRENSHAW COMMUNITY HOSPITAL         101 HOSPITAL CIRCLE

  state zip_code                           hospital_ownership  \
0    AL    36301  Government - Hospital District or Authority
1    AL    35957  Government - Hospital District or Authority
2    AL    35630                                  Proprietary
3    AL    36467               Voluntary non-profit - Private
4    AL    36049                                  Proprietary

   hospital_overall_rating  count_of_mort_measures_better  \
0                      3.0                            1.0
1                      2.0                            0.0
2                      1.0                            0.0
3                      1.0                            0.0
4                      0.0                            0.0

   count_of_safety_measures_better  count_of_readm_measures_better
0                              2.0                             1.0
1                              0.0                             0.0
2                              3.0                             0.0
3                              0.0                             0.0
4                              0.0                             0.0

C:\Windows\Temp\ipykernel_8872\3444041831.py:65: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['hospital_overall_rating'].fillna(0, inplace=True)
C:\Windows\Temp\ipykernel_8872\3444041831.py:66: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['count_of_mort_measures_better'].fillna(0, inplace=True)
C:\Windows\Temp\ipykernel_8872\3444041831.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['count_of_safety_measures_better'].fillna(0, inplace=True)
C:\Windows\Temp\ipykernel_8872\3444041831.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['count_of_readm_measures_better'].fillna(0, inplace=True)

In [20]:
# Check for duplicates
duplicates = df.duplicated()
if duplicates.any():
    print("Duplicates found:")
    print(df[duplicates])
else:
    print("No duplicates found.")

No duplicates found.

In [21]:
# save the cleaned DataFrame to a new CSV file
cleaned_df.to_csv('data/general_cleaned.csv', index=False)